spring:
  security:
    filter:
      order: -100
    jwt:
      key: ffdfgfhfg
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    cors:
      origin: '*'
      credentials: false
      methods: '*'